data1 <- read_excel(file.choose(), sheet = 2)
show(data1)
zone1 <- ifelse(data1$Zone=="Ciutat Vella", 1, 0)
zone2 <- ifelse(data1$Zone== "Eixample", 1, 0)
zone3 <- ifelse(data1$Zone== "Gràcia", 1, 0)
zone4 <- ifelse(data1$Zone== "Horta - Guinardó", 1, 0)
zone5 <- ifelse(data1$Zone== "Les Corts", 1, 0)
zone6 <- ifelse(data1$Zone== "Nou Barris", 1, 0)
zone7 <- ifelse(data1$Zone== "Sant Andreu", 1, 0)
zone8 <- ifelse(data1$Zone== "Sant Marti", 1, 0)
zone9 <- ifelse(data1$Zone== "Sants - Montjuïc", 1, 0) #Sarria - Sant Gervasi left
qplot((data1$m), data1$Price)
qplot(data1$m^2,data1$Price)
qplot(log(data1$m), data1$Price)
qplot((data1$Price),(data1$m)^2)
model29 <- lm(Price ~ m^2 + zone1*(m^2)+zone2*(m^2)+zone3*(m^2)+zone4*(m^2)+zone5*(m^2)+zone6*(m^2)+zone7*(m^2)+zone8*(m^2)+zone9*(m^2)+(zone1*Rooms)+(zone2*Rooms)+(zone3*Rooms)+(zone4*Rooms)+(zone5*Rooms)+(zone6*Rooms)+(zone7*Rooms)+(zone8*Rooms)+(zone9*Rooms)+(zone1*Bathrooms)+(zone2*Bathrooms)+(zone3*Bathrooms)+(zone4*Bathrooms)+(zone5*Bathrooms)+(zone6*Bathrooms)+(zone7*Bathrooms)+(zone8*Bathrooms)+(zone9*Bathrooms)+(zone1*Elevator)+(zone2*Elevator)+(zone3*Elevator)+(zone4*Elevator)+(zone5*Elevator)+(zone6*Elevator)+(zone7*Elevator)+(zone8*Elevator)+(zone9*Elevator)+(zone1*Atico)+(zone2*Atico)+(zone3*Atico)+(zone4*Atico)+(zone5*Atico)+(zone6*Atico)+(zone7*Atico)+(zone8*Atico)+(zone9*Atico)+(zone1*Terrasse)+(zone2*Terrasse)+(zone3*Terrasse)+(zone4*Terrasse)+(zone5*Terrasse)+(zone6*Terrasse)+(zone7*Terrasse)+(zone8*Terrasse)+(zone9*Terrasse)+(zone1*Parking)+(zone2*Parking)+(zone3*Parking)+(zone4*Parking)+(zone5*Parking)+(zone6*Parking)+(zone7*Parking)+(zone8*Parking)+(zone9*Parking)+(zone1*Kitchen)+(zone2*Kitchen)+(zone3*Kitchen)+(zone4*Kitchen)+(zone5*Kitchen)+(zone6*Kitchen)+(zone7*Kitchen)+(zone8*Kitchen)+(zone9*Kitchen)+(zone1*Type)+(zone2*Type)+(zone3*Type)+(zone4*Type)+(zone5*Type)+(zone6*Type)+(zone7*Type)+(zone8*Type)+(zone9*Type)+(zone1*Yard)+(zone2*Yard)+(zone3*Yard)+(zone4*Yard)+(zone5*Yard)+(zone6*Yard)+(zone7*Yard)+(zone8*Yard)+(zone9*Yard)+(zone1*Rooms*Bathrooms)+(zone2*Rooms*Bathrooms)+(zone3*Rooms*Bathrooms)+(zone4*Rooms*Bathrooms)+(zone5*Rooms*Bathrooms)+(zone6*Rooms*Bathrooms)+(zone7*Rooms*Bathrooms)+(zone8*Rooms*Bathrooms)+(zone9*Rooms*Bathrooms), data=data1)
summary(model29)
acf(residuals(model29))
hist(residuals(model29), breaks=30)
plot(fitted.values(model29), residuals(model29))      
plot(data1$m^2, residuals(model29))
##DISCLAIMER REGARDING CHANGING COLUMN NAMES.!!
prediction <- read_excel(file.choose(), sheet = 1)
zone1 <- ifelse(prediction$Zone=="Ciutat Vella", 1, 0)
zone2 <- ifelse(prediction$Zone== "Eixample", 1, 0)
zone3 <- ifelse(prediction$Zone== "Gràcia", 1, 0)
zone4 <- ifelse(prediction$Zone== "Horta - Guinardó", 1, 0)
zone5 <- ifelse(prediction$Zone== "Les Corts", 1, 0)
zone6 <- ifelse(prediction$Zone== "Nou Barris", 1, 0)
zone7 <- ifelse(prediction$Zone== "Sant Andreu", 1, 0)
zone8 <- ifelse(prediction$Zone== "Sant Marti", 1, 0)
zone9 <- ifelse(prediction$Zone== "Sants - Montjuïc", 1, 0)
prices <- predict(model29, newdata=prediction)
write_xlsx(as.data.frame(prices), path="predicted_prices.xlsx")



